---

image: python:3.9.4-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -Ur requirements.txt
  - echo isort $(isort --version-number)
  - black --version
  - flake8 --version
  - pylint --version

build:
  stage: build
  except:
    - tags
  script:
    - isort --check --diff *.py library/*.py tests/*.py
    - black --check *.py library/*.py tests/*.py
    - flake8 *.py library/*.py tests/*.py
    - pylint *.py library/*.py tests/*.py
    - pytest -v --cov-report term-missing --cov=library tests
    - python wordpuzzle.py -l cadevrsoi
    - python wordpuzzle.py --version
    - python wordpuzzle.py --help
