---

image: python:3.9.4-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U -r requirements.txt
  - flake8 --version
  - pylint --version
  - yapf --version
  - echo isort $(isort --version-number)

build:
  stage: build
  except:
    - tags
  script:
    - isort --check --diff *.py tests/*.py lib/*.py
    - yapf --style google --diff --parallel *.py tests/*.py lib/*.py
    - flake8 *.py tests/*.py lib/*.py
    - pylint *.py tests/*.py lib/*.py
    - pytest -v tests
    - python wordpuzzle.py -l cadevrsoi
    - python wordpuzzle.py --version
    - python wordpuzzle.py --help
