name: test python wordpuzzle

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:

  build:

    name: test python wordpuzzle
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
        os: [ubuntu-latest, maxos-latest]

    steps:

      - name: shallow checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1

      - name: check and test
        run: |
          python3 -V
          pip3 install -r requirements.txt
          yapf3 --style google --diff --parallel wordpuzzle.py tests/testwordpuzzle.py tests/__init__.py utils/__init__.py utils/filters.py
          pylint3 wordpuzzle.py tests/testwordpuzzle.py tests/__init__.py utils/__init__.py utils/filters.py
          pytest3 -v tests/test*.py
          python3 wordpuzzle.py -h
          python3 wordpuzzle.py --version
