---

name: python-wordpuzzle

on:
  push:
    branches:
      - master
      - 'feature*'
  schedule:
    - cron: '0 0 * * *'  # daily

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          echo isort $(isort --version-number)
          black --version
          flake8 --version
          pylint --version

      - name: validate
        run: |
          isort --check --diff *.py lib/*.py tests/*.py
          black --check *.py lib/*.py tests/*.py
          flake8 *.py lib/*.py tests/*.py
          pylint *.py lib/*.py tests/*.py

      - name: tests
        run: pytest -v --cov-report term-missing --cov=lib tests

      - name: run example
        run: python wordpuzzle.py -l cadevrsoi

      - name: run version
        run: python wordpuzzle.py --version

      - name: run help
        run: python wordpuzzle.py --help
