---

name: python-wordpuzzle

on:
  push:
    branches:
      - master
      - "feature*"
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: setup
        run: |
          uv sync
          uv pip list

      - name: check
        run: |
          uv run ruff format --check *.py library/*.py tests/*.py
          uv run ruff check *.py library/*.py tests/*.py

      - name: tests
        run: uv run pytest -v --cov-report term-missing --cov=library tests

      - name: run example
        run: uv run python wordpuzzle.py -s 7 -l cadevrsoi

      - name: run version
        run: uv run python wordpuzzle.py --version

      - name: run help
        run: uv run python wordpuzzle.py --help
