---

name: python-wordpuzzle

on:
  push:
    branches:
      - master
      - 'feature*'
  schedule:
    - cron: '0 0 * * *'  # daily

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          flake8 --version
          pylint --version
          yapf --version
          echo isort $(isort --version-number)

      - name: validate
        run: |
          isort --check --diff *.py tests/*.py lib/*.py
          yapf --style google --diff --parallel *.py tests/*.py lib/*.py
          flake8 *.py tests/*.py lib/*.py
          pylint *.py tests/*.py lib/*.py

      - name: tests
        run: |
          pytest -v tests

      - name: run example
        run: python wordpuzzle.py -l cadevrsoi

      - name: run version
        run: python wordpuzzle.py --version

      - name: run help
        run: python wordpuzzle.py --help
